class SuraModel {
  final String suraNameAr;
  final String suraNameEn;
  final String suraNumber; 
  final int versesNum;

  SuraModel({
    required this.suraNameAr,
    required this.suraNameEn,
    required this.suraNumber, 
    required this.versesNum,
  });

  static List<SuraModel> getAllSurahs = [
    SuraModel(suraNameAr: "الفاتحة", suraNameEn: "Al-Fatiha", suraNumber: "1", versesNum: 7),
    SuraModel(suraNameAr: "البقرة", suraNameEn: "Al-Baqarah", suraNumber: "2", versesNum: 286),
    SuraModel(suraNameAr: "آل عمران", suraNameEn: "Ali 'Imran", suraNumber: "3", versesNum: 200),
    SuraModel(suraNameAr: "النساء", suraNameEn: "An-Nisa", suraNumber: "4", versesNum: 176),
    SuraModel(suraNameAr: "المائدة", suraNameEn: "Al-Ma'idah", suraNumber: "5", versesNum: 120),
    SuraModel(suraNameAr: "الأنعام", suraNameEn: "Al-An'am", suraNumber: "6", versesNum: 165),
    SuraModel(suraNameAr: "الأعراف", suraNameEn: "Al-A'raf", suraNumber: "7", versesNum: 206),
    SuraModel(suraNameAr: "الأنفال", suraNameEn: "Al-Anfal", suraNumber: "8", versesNum: 75),
    SuraModel(suraNameAr: "التوبة", suraNameEn: "At-Tawbah", suraNumber: "9", versesNum: 129),
    SuraModel(suraNameAr: "يونس", suraNameEn: "Yunus", suraNumber: "10", versesNum: 109),
    SuraModel(suraNameAr: "هود", suraNameEn: "Hud", suraNumber: "11", versesNum: 123),
    SuraModel(suraNameAr: "يوسف", suraNameEn: "Yusuf", suraNumber: "12", versesNum: 111),
    SuraModel(suraNameAr: "الرعد", suraNameEn: "Ar-Ra'd", suraNumber: "13", versesNum: 43),
    SuraModel(suraNameAr: "إبراهيم", suraNameEn: "Ibrahim", suraNumber: "14", versesNum: 52),
    SuraModel(suraNameAr: "الحجر", suraNameEn: "Al-Hijr", suraNumber: "15", versesNum: 99),
    SuraModel(suraNameAr: "النحل", suraNameEn: "An-Nahl", suraNumber: "16", versesNum: 128),
    SuraModel(suraNameAr: "الإسراء", suraNameEn: "Al-Isra", suraNumber: "17", versesNum: 111),
    SuraModel(suraNameAr: "الكهف", suraNameEn: "Al-Kahf", suraNumber: "18", versesNum: 110),
    SuraModel(suraNameAr: "مريم", suraNameEn: "Maryam", suraNumber: "19", versesNum: 98),
    SuraModel(suraNameAr: "طه", suraNameEn: "Taha", suraNumber: "20", versesNum: 135),
    SuraModel(suraNameAr: "الأنбиاء", suraNameEn: "Al-Anbiya", suraNumber: "21", versesNum: 112),
    SuraModel(suraNameAr: "الحج", suraNameEn: "Al-Hajj", suraNumber: "22", versesNum: 78),
    SuraModel(suraNameAr: "المؤمنون", suraNameEn: "Al-Mu'minun", suraNumber: "23", versesNum: 118),
    SuraModel(suraNameAr: "النور", suraNameEn: "An-Nur", suraNumber: "24", versesNum: 64),
    SuraModel(suraNameAr: "الفرقان", suraNameEn: "Al-Furqan", suraNumber: "25", versesNum: 77),
    SuraModel(suraNameAr: "الشعراء", suraNameEn: "Ash-Shu'ara", suraNumber: "26", versesNum: 227),
    SuraModel(suraNameAr: "النمل", suraNameEn: "An-Naml", suraNumber: "27", versesNum: 93),
    SuraModel(suraNameAr: "القصص", suraNameEn: "Al-Qasas", suraNumber: "28", versesNum: 88),
    SuraModel(suraNameAr: "العنكبوت", suraNameEn: "Al-Ankabut", suraNumber: "29", versesNum: 69),
    SuraModel(suraNameAr: "الروم", suraNameEn: "Ar-Rum", suraNumber: "30", versesNum: 60),
    SuraModel(suraNameAr: "لقمان", suraNameEn: "Luqman", suraNumber: "31", versesNum: 34),
    SuraModel(suraNameAr: "السجدة", suraNameEn: "As-Sajdah", suraNumber: "32", versesNum: 30),
    SuraModel(suraNameAr: "الأحزاب", suraNameEn: "Al-Ahzab", suraNumber: "33", versesNum: 73),
    SuraModel(suraNameAr: "سبأ", suraNameEn: "Saba", suraNumber: "34", versesNum: 54),
    SuraModel(suraNameAr: "فاطر", suraNameEn: "Fatir", suraNumber: "35", versesNum: 45),
    SuraModel(suraNameAr: "يس", suraNameEn: "Ya-Sin", suraNumber: "36", versesNum: 83),
    SuraModel(suraNameAr: "الصافات", suraNameEn: "As-Saffat", suraNumber: "37", versesNum: 182),
    SuraModel(suraNameAr: "ص", suraNameEn: "Sad", suraNumber: "38", versesNum: 88),
    SuraModel(suraNameAr: "الزمر", suraNameEn: "Az-Zumar", suraNumber: "39", versesNum: 75),
    SuraModel(suraNameAr: "غافر", suraNameEn: "Ghafir", suraNumber: "40", versesNum: 85),
    SuraModel(suraNameAr: "فصلت", suraNameEn: "Fussilat", suraNumber: "41", versesNum: 54),
    SuraModel(suraNameAr: "الشورى", suraNameEn: "Ash-Shura", suraNumber: "42", versesNum: 53),
    SuraModel(suraNameAr: "الزخرف", suraNameEn: "Az-Zukhruf", suraNumber: "43", versesNum: 89),
    SuraModel(suraNameAr: "الدخان", suraNameEn: "Ad-Dukhan", suraNumber: "44", versesNum: 59),
    SuraModel(suraNameAr: "الجاثية", suraNameEn: "Al-Jathiyah", suraNumber: "45", versesNum: 37),
    SuraModel(suraNameAr: "الأحقاف", suraNameEn: "Al-Ahqaf", suraNumber: "46", versesNum: 35),
    SuraModel(suraNameAr: "محمد", suraNameEn: "Muhammad", suraNumber: "47", versesNum: 38),
    SuraModel(suraNameAr: "الفتح", suraNameEn: "Al-Fath", suraNumber: "48", versesNum: 29),
    SuraModel(suraNameAr: "الحجرات", suraNameEn: "Al-Hujurat", suraNumber: "49", versesNum: 18),
    SuraModel(suraNameAr: "ق", suraNameEn: "Qaf", suraNumber: "50", versesNum: 45),
    SuraModel(suraNameAr: "الذاريات", suraNameEn: "Adh-Dhariyat", suraNumber: "51", versesNum: 60),
    SuraModel(suraNameAr: "الطور", suraNameEn: "At-Tur", suraNumber: "52", versesNum: 49),
    SuraModel(suraNameAr: "النجم", suraNameEn: "An-Najm", suraNumber: "53", versesNum: 62),
    SuraModel(suraNameAr: "القمر", suraNameEn: "Al-Qamar", suraNumber: "54", versesNum: 55),
    SuraModel(suraNameAr: "الرحمن", suraNameEn: "Ar-Rahman", suraNumber: "55", versesNum: 78),
    SuraModel(suraNameAr: "الواقعة", suraNameEn: "Al-Waqi'ah", suraNumber: "56", versesNum: 96),
    SuraModel(suraNameAr: "الحديد", suraNameEn: "Al-Hadid", suraNumber: "57", versesNum: 29),
    SuraModel(suraNameAr: "المجادلة", suraNameEn: "Al-Mujadila", suraNumber: "58", versesNum: 22),
    SuraModel(suraNameAr: "الحشر", suraNameEn: "Al-Hashr", suraNumber: "59", versesNum: 24),
    SuraModel(suraNameAr: "الممتحنة", suraNameEn: "Al-Mumtahanah", suraNumber: "60", versesNum: 13),
    SuraModel(suraNameAr: "الصف", suraNameEn: "As-Saff", suraNumber: "61", versesNum: 14),
    SuraModel(suraNameAr: "الجمعة", suraNameEn: "Al-Jumu'ah", suraNumber: "62", versesNum: 11),
    SuraModel(suraNameAr: "المنافقون", suraNameEn: "Al-Munafiqun", suraNumber: "63", versesNum: 11),
    SuraModel(suraNameAr: "التغابن", suraNameEn: "At-Taghabun", suraNumber: "64", versesNum: 18),
    SuraModel(suraNameAr: "الطلاق", suraNameEn: "At-Talaq", suraNumber: "65", versesNum: 12),
    SuraModel(suraNameAr: "التحريم", suraNameEn: "At-Tahrim", suraNumber: "66", versesNum: 12),
    SuraModel(suraNameAr: "الملك", suraNameEn: "Al-Mulk", suraNumber: "67", versesNum: 30),
    SuraModel(suraNameAr: "القلم", suraNameEn: "Al-Qalam", suraNumber: "68", versesNum: 52),
    SuraModel(suraNameAr: "الحاقة", suraNameEn: "Al-Haqqah", suraNumber: "69", versesNum: 52),
    SuraModel(suraNameAr: "المعارج", suraNameEn: "Al-Ma'arij", suraNumber: "70", versesNum: 44),
    SuraModel(suraNameAr: "نوح", suraNameEn: "Nuh", suraNumber: "71", versesNum: 28),
    SuraModel(suraNameAr: "الجن", suraNameEn: "Al-Jinn", suraNumber: "72", versesNum: 28),
    SuraModel(suraNameAr: "المزمل", suraNameEn: "Al-Muzzammil", suraNumber: "73", versesNum: 20),
    SuraModel(suraNameAr: "المدثر", suraNameEn: "Al-Muddaththir", suraNumber: "74", versesNum: 56),
    SuraModel(suraNameAr: "القيامة", suraNameEn: "Al-Qiyamah", suraNumber: "75", versesNum: 40),
    SuraModel(suraNameAr: "الإنسان", suraNameEn: "Al-Insan", suraNumber: "76", versesNum: 31),
    SuraModel(suraNameAr: "المرسلات", suraNameEn: "Al-Mursalat", suraNumber: "77", versesNum: 50),
    SuraModel(suraNameAr: "النبأ", suraNameEn: "An-Naba", suraNumber: "78", versesNum: 40),
    SuraModel(suraNameAr: "النازعات", suraNameEn: "An-Nazi'at", suraNumber: "79", versesNum: 46),
    SuraModel(suraNameAr: "عبس", suraNameEn: "Abasa", suraNumber: "80", versesNum: 42),
    SuraModel(suraNameAr: "التكوير", suraNameEn: "At-Takwir", suraNumber: "81", versesNum: 29),
    SuraModel(suraNameAr: "الانفطار", suraNameEn: "Al-Infitar", suraNumber: "82", versesNum: 19),
    SuraModel(suraNameAr: "المطففين", suraNameEn: "Al-Mutaffifin", suraNumber: "83", versesNum: 36),
    SuraModel(suraNameAr: "الانشقاق", suraNameEn: "Al-Inshiqaq", suraNumber: "84", versesNum: 25),
    SuraModel(suraNameAr: "البروج", suraNameEn: "Al-Buruj", suraNumber: "85", versesNum: 22),
    SuraModel(suraNameAr: "الطارق", suraNameEn: "At-Tariq", suraNumber: "86", versesNum: 17),
    SuraModel(suraNameAr: "الأعلى", suraNameEn: "Al-A'la", suraNumber: "87", versesNum: 19),
    SuraModel(suraNameAr: "الغاشية", suraNameEn: "Al-Gashiyah", suraNumber: "88", versesNum: 26),
    SuraModel(suraNameAr: "الفجر", suraNameEn: "Al-Fajr", suraNumber: "89", versesNum: 30),
    SuraModel(suraNameAr: "البلد", suraNameEn: "Al-Balad", suraNumber: "90", versesNum: 20),
    SuraModel(suraNameAr: "الشمس", suraNameEn: "Ash-Shams", suraNumber: "91", versesNum: 15),
    SuraModel(suraNameAr: "الليل", suraNameEn: "Al-Layl", suraNumber: "92", versesNum: 21),
    SuraModel(suraNameAr: "الضحى", suraNameEn: "Ad-Duha", suraNumber: "93", versesNum: 11),
    SuraModel(suraNameAr: "الشرح", suraNameEn: "Ash-Sharh", suraNumber: "94", versesNum: 8),
    SuraModel(suraNameAr: "التين", suraNameEn: "At-Tin", suraNumber: "95", versesNum: 8),
    SuraModel(suraNameAr: "العلق", suraNameEn: "Al-Alaq", suraNumber: "96", versesNum: 19),
    SuraModel(suraNameAr: "القدر", suraNameEn: "Al-Qadr", suraNumber: "97", versesNum: 5),
    SuraModel(suraNameAr: "البينة", suraNameEn: "Al-Bayyinah", suraNumber: "98", versesNum: 8),
    SuraModel(suraNameAr: "الزلزلة", suraNameEn: "Az-Zalzalah", suraNumber: "99", versesNum: 8),
    SuraModel(suraNameAr: "العاديات", suraNameEn: "Al-Adiyat", suraNumber: "100", versesNum: 11),
    SuraModel(suraNameAr: "القارعة", suraNameEn: "Al-Qari'ah", suraNumber: "101", versesNum: 11),
    SuraModel(suraNameAr: "التكاثر", suraNameEn: "At-Takathur", suraNumber: "102", versesNum: 8),
    SuraModel(suraNameAr: "العصر", suraNameEn: "Al-Asr", suraNumber: "103", versesNum: 3),
    SuraModel(suraNameAr: "الهمزة", suraNameEn: "Al-Humazah", suraNumber: "104", versesNum: 9),
    SuraModel(suraNameAr: "الفيل", suraNameEn: "Al-Fil", suraNumber: "105", versesNum: 5),
    SuraModel(suraNameAr: "قريش", suraNameEn: "Quraysh", suraNumber: "106", versesNum: 4),
    SuraModel(suraNameAr: "الماعون", suraNameEn: "Al-Ma'un", suraNumber: "107", versesNum: 7),
    SuraModel(suraNameAr: "الكوثر", suraNameEn: "Al-Kawthar", suraNumber: "108", versesNum: 3),
    SuraModel(suraNameAr: "الكافرون", suraNameEn: "Al-Kafirun", suraNumber: "109", versesNum: 6),
    SuraModel(suraNameAr: "النصر", suraNameEn: "An-Nasr", suraNumber: "110", versesNum: 3),
    SuraModel(suraNameAr: "المسد", suraNameEn: "Al-Masad", suraNumber: "111", versesNum: 5),
    SuraModel(suraNameAr: "الإخلاص", suraNameEn: "Al-Ikhlas", suraNumber: "112", versesNum: 4),
    SuraModel(suraNameAr: "الفلق", suraNameEn: "Al-Falaq", suraNumber: "113", versesNum: 5),
    SuraModel(suraNameAr: "الناس", suraNameEn: "An-Nas", suraNumber: "114", versesNum: 6),
  ];
}



// class SuraModel {
//   final String suraNameAr;
//   final String suraNameEn;
//   final int suraNumber;
//   final int versesNum;
//   SuraModel({
//     required this.suraNameAr,
//     required this.suraNameEn,
//     required this.suraNumber,
//     required this.versesNum,
//   });
//   static List<SuraModel> getAllSurahs = [
//       SuraModel(suraNameAr: "الفاتحة", suraNameEn: "Al-Fatiha", suraNumber: 1, versesNum: 7),
//       SuraModel(suraNameAr: "البقرة", suraNameEn: "Al-Baqarah", suraNumber: 2, versesNum: 286),
//       SuraModel(suraNameAr: "آل عمران", suraNameEn: "Ali 'Imran", suraNumber: 3, versesNum: 200),
//       SuraModel(suraNameAr: "النساء", suraNameEn: "An-Nisa", suraNumber: 4, versesNum: 176),
//       SuraModel(suraNameAr: "المائدة", suraNameEn: "Al-Ma'idah", suraNumber: 5, versesNum: 120),
//       SuraModel(suraNameAr: "الأنعام", suraNameEn: "Al-An'am", suraNumber: 6, versesNum: 165),
//       SuraModel(suraNameAr: "الأعراف", suraNameEn: "Al-A'raf", suraNumber: 7, versesNum: 206),
//       SuraModel(suraNameAr: "الأنفال", suraNameEn: "Al-Anfal", suraNumber: 8, versesNum: 75),
//       SuraModel(suraNameAr: "التوبة", suraNameEn: "At-Tawbah", suraNumber: 9, versesNum: 129),
//       SuraModel(suraNameAr: "يونس", suraNameEn: "Yunus", suraNumber: 10, versesNum: 109),
//       SuraModel(suraNameAr: "هود", suraNameEn: "Hud", suraNumber: 11, versesNum: 123),
//       SuraModel(suraNameAr: "يوسف", suraNameEn: "Yusuf", suraNumber: 12, versesNum: 111),
//       SuraModel(suraNameAr: "الرعد", suraNameEn: "Ar-Ra'd", suraNumber: 13, versesNum: 43),
//       SuraModel(suraNameAr: "إبراهيم", suraNameEn: "Ibrahim", suraNumber: 14, versesNum: 52),
//       SuraModel(suraNameAr: "الحجر", suraNameEn: "Al-Hijr", suraNumber: 15, versesNum: 99),
//       SuraModel(suraNameAr: "النحل", suraNameEn: "An-Nahl", suraNumber: 16, versesNum: 128),
//       SuraModel(suraNameAr: "الإسراء", suraNameEn: "Al-Isra", suraNumber: 17, versesNum: 111),
//       SuraModel(suraNameAr: "الكهف", suraNameEn: "Al-Kahf", suraNumber: 18, versesNum: 110),
//       SuraModel(suraNameAr: "مريم", suraNameEn: "Maryam", suraNumber: 19, versesNum: 98),
//       SuraModel(suraNameAr: "طه", suraNameEn: "Taha", suraNumber: 20, versesNum: 135),
//       SuraModel(suraNameAr: "الأنبياء", suraNameEn: "Al-Anbiya", suraNumber: 21, versesNum: 112),
//       SuraModel(suraNameAr: "الحج", suraNameEn: "Al-Hajj", suraNumber: 22, versesNum: 78),
//       SuraModel(suraNameAr: "المؤمنون", suraNameEn: "Al-Mu'minun", suraNumber: 23, versesNum: 118),
//       SuraModel(suraNameAr: "النور", suraNameEn: "An-Nur", suraNumber: 24, versesNum: 64),
//       SuraModel(suraNameAr: "الفرقان", suraNameEn: "Al-Furqan", suraNumber: 25, versesNum: 77),
//       SuraModel(suraNameAr: "الشعراء", suraNameEn: "Ash-Shu'ara", suraNumber: 26, versesNum: 227),
//       SuraModel(suraNameAr: "النمل", suraNameEn: "An-Naml", suraNumber: 27, versesNum: 93),
//       SuraModel(suraNameAr: "القصص", suraNameEn: "Al-Qasas", suraNumber: 28, versesNum: 88),
//       SuraModel(suraNameAr: "العنكبوت", suraNameEn: "Al-Ankabut", suraNumber: 29, versesNum: 69),
//       SuraModel(suraNameAr: "الروم", suraNameEn: "Ar-Rum", suraNumber: 30, versesNum: 60),
//       SuraModel(suraNameAr: "لقمان", suraNameEn: "Luqman", suraNumber: 31, versesNum: 34),
//       SuraModel(suraNameAr: "السجدة", suraNameEn: "As-Sajdah", suraNumber: 32, versesNum: 30),
//       SuraModel(suraNameAr: "الأحزاب", suraNameEn: "Al-Ahzab", suraNumber: 33, versesNum: 73),
//       SuraModel(suraNameAr: "سبأ", suraNameEn: "Saba", suraNumber: 34, versesNum: 54),
//       SuraModel(suraNameAr: "فاطر", suraNameEn: "Fatir", suraNumber: 35, versesNum: 45),
//       SuraModel(suraNameAr: "يس", suraNameEn: "Ya-Sin", suraNumber: 36, versesNum: 83),
//       SuraModel(suraNameAr: "الصافات", suraNameEn: "As-Saffat", suraNumber: 37, versesNum: 182),
//       SuraModel(suraNameAr: "ص", suraNameEn: "Sad", suraNumber: 38, versesNum: 88),
//       SuraModel(suraNameAr: "الزمر", suraNameEn: "Az-Zumar", suraNumber: 39, versesNum: 75),
//       SuraModel(suraNameAr: "غافر", suraNameEn: "Ghafir", suraNumber: 40, versesNum: 85),
//       SuraModel(suraNameAr: "فصلت", suraNameEn: "Fussilat", suraNumber: 41, versesNum: 54),
//       SuraModel(suraNameAr: "الشورى", suraNameEn: "Ash-Shura", suraNumber: 42, versesNum: 53),
//       SuraModel(suraNameAr: "الزخرف", suraNameEn: "Az-Zukhruf", suraNumber: 43, versesNum: 89),
//       SuraModel(suraNameAr: "الدخان", suraNameEn: "Ad-Dukhan", suraNumber: 44, versesNum: 59),
//       SuraModel(suraNameAr: "الجاثية", suraNameEn: "Al-Jathiyah", suraNumber: 45, versesNum: 37),
//       SuraModel(suraNameAr: "الأحقاف", suraNameEn: "Al-Ahqaf", suraNumber: 46, versesNum: 35),
//       SuraModel(suraNameAr: "محمد", suraNameEn: "Muhammad", suraNumber: 47, versesNum: 38),
//       SuraModel(suraNameAr: "الفتح", suraNameEn: "Al-Fath", suraNumber: 48, versesNum: 29),
//       SuraModel(suraNameAr: "الحجرات", suraNameEn: "Al-Hujurat", suraNumber: 49, versesNum: 18),
//       SuraModel(suraNameAr: "ق", suraNameEn: "Qaf", suraNumber: 50, versesNum: 45),
//       SuraModel(suraNameAr: "الذاريات", suraNameEn: "Adh-Dhariyat", suraNumber: 51, versesNum: 60),
//       SuraModel(suraNameAr: "الطور", suraNameEn: "At-Tur", suraNumber: 52, versesNum: 49),
//       SuraModel(suraNameAr: "النجم", suraNameEn: "An-Najm", suraNumber: 53, versesNum: 62),
//       SuraModel(suraNameAr: "القمر", suraNameEn: "Al-Qamar", suraNumber: 54, versesNum: 55),
//       SuraModel(suraNameAr: "الرحمن", suraNameEn: "Ar-Rahman", suraNumber: 55, versesNum: 78),
//       SuraModel(suraNameAr: "الواقعة", suraNameEn: "Al-Waqi'ah", suraNumber: 56, versesNum: 96),
//       SuraModel(suraNameAr: "الحديد", suraNameEn: "Al-Hadid", suraNumber: 57, versesNum: 29),
//       SuraModel(suraNameAr: "المجادلة", suraNameEn: "Al-Mujadila", suraNumber: 58, versesNum: 22),
//       SuraModel(suraNameAr: "الحشر", suraNameEn: "Al-Hashr", suraNumber: 59, versesNum: 24),
//       SuraModel(suraNameAr: "الممتحنة", suraNameEn: "Al-Mumtahanah", suraNumber: 60, versesNum: 13),
//       SuraModel(suraNameAr: "الصف", suraNameEn: "As-Saff", suraNumber: 61, versesNum: 14),
//       SuraModel(suraNameAr: "الجمعة", suraNameEn: "Al-Jumu'ah", suraNumber: 62, versesNum: 11),
//       SuraModel(suraNameAr: "المنافقون", suraNameEn: "Al-Munafiqun", suraNumber: 63, versesNum: 11),
//       SuraModel(suraNameAr: "التغابن", suraNameEn: "At-Taghabun", suraNumber: 64, versesNum: 18),
//       SuraModel(suraNameAr: "الطلاق", suraNameEn: "At-Talaq", suraNumber: 65, versesNum: 12),
//       SuraModel(suraNameAr: "التحريم", suraNameEn: "At-Tahrim", suraNumber: 66, versesNum: 12),
//       SuraModel(suraNameAr: "الملك", suraNameEn: "Al-Mulk", suraNumber: 67, versesNum: 30),
//       SuraModel(suraNameAr: "القلم", suraNameEn: "Al-Qalam", suraNumber: 68, versesNum: 52),
//       SuraModel(suraNameAr: "الحاقة", suraNameEn: "Al-Haqqah", suraNumber: 69, versesNum: 52),
//       SuraModel(suraNameAr: "المعارج", suraNameEn: "Al-Ma'arij", suraNumber: 70, versesNum: 44),
//       SuraModel(suraNameAr: "نوح", suraNameEn: "Nuh", suraNumber: 71, versesNum: 28),
//       SuraModel(suraNameAr: "الجن", suraNameEn: "Al-Jinn", suraNumber: 72, versesNum: 28),
//       SuraModel(suraNameAr: "المزمل", suraNameEn: "Al-Muzzammil", suraNumber: 73, versesNum: 20),
//       SuraModel(suraNameAr: "المدثر", suraNameEn: "Al-Muddaththir", suraNumber: 74, versesNum: 56),
//       SuraModel(suraNameAr: "القيامة", suraNameEn: "Al-Qiyamah", suraNumber: 75, versesNum: 40),
//       SuraModel(suraNameAr: "الإنسان", suraNameEn: "Al-Insan", suraNumber: 76, versesNum: 31),
//       SuraModel(suraNameAr: "المرسلات", suraNameEn: "Al-Mursalat", suraNumber: 77, versesNum: 50),
//       SuraModel(suraNameAr: "النبأ", suraNameEn: "An-Naba", suraNumber: 78, versesNum: 40),
//       SuraModel(suraNameAr: "النازعات", suraNameEn: "An-Nazi'at", suraNumber: 79, versesNum: 46),
//       SuraModel(suraNameAr: "عبس", suraNameEn: "Abasa", suraNumber: 80, versesNum: 42),
//       SuraModel(suraNameAr: "التكوير", suraNameEn: "At-Takwir", suraNumber: 81, versesNum: 29),
//       SuraModel(suraNameAr: "الانفطار", suraNameEn: "Al-Infitar", suraNumber: 82, versesNum: 19),
//       SuraModel(suraNameAr: "المطففين", suraNameEn: "Al-Mutaffifin", suraNumber: 83, versesNum: 36),
//       SuraModel(suraNameAr: "الانشقاق", suraNameEn: "Al-Inshiqaq", suraNumber: 84, versesNum: 25),
//       SuraModel(suraNameAr: "البروج", suraNameEn: "Al-Buruj", suraNumber: 85, versesNum: 22),
//       SuraModel(suraNameAr: "الطارق", suraNameEn: "At-Tariq", suraNumber: 86, versesNum: 17),
//       SuraModel(suraNameAr: "الأعلى", suraNameEn: "Al-A'la", suraNumber: 87, versesNum: 19),
//       SuraModel(suraNameAr: "الغاشية", suraNameEn: "Al-Ghashiyah", suraNumber: 88, versesNum: 26),
//       SuraModel(suraNameAr: "الفجر", suraNameEn: "Al-Fajr", suraNumber: 89, versesNum: 30),
//       SuraModel(suraNameAr: "البلد", suraNameEn: "Al-Balad", suraNumber: 90, versesNum: 20),
//       SuraModel(suraNameAr: "الشمس", suraNameEn: "Ash-Shams", suraNumber: 91, versesNum: 15),
//       SuraModel(suraNameAr: "الليل", suraNameEn: "Al-Layl", suraNumber: 92, versesNum: 21),
//       SuraModel(suraNameAr: "الضحى", suraNameEn: "Ad-Duha", suraNumber: 93, versesNum: 11),
//       SuraModel(suraNameAr: "الشرح", suraNameEn: "Ash-Sharh", suraNumber: 94, versesNum: 8),
//       SuraModel(suraNameAr: "التين", suraNameEn: "At-Tin", suraNumber: 95, versesNum: 8),
//       SuraModel(suraNameAr: "العلق", suraNameEn: "Al-Alaq", suraNumber: 96, versesNum: 19),
//       SuraModel(suraNameAr: "القدر", suraNameEn: "Al-Qadr", suraNumber: 97, versesNum: 5),
//       SuraModel(suraNameAr: "البينة", suraNameEn: "Al-Bayyinah", suraNumber: 98, versesNum: 8),
//       SuraModel(suraNameAr: "الزلزلة", suraNameEn: "Az-Zalzalah", suraNumber: 99, versesNum: 8),
//       SuraModel(suraNameAr: "العاديات", suraNameEn: "Al-Adiyat", suraNumber: 100, versesNum: 11),
//       SuraModel(suraNameAr: "القارعة", suraNameEn: "Al-Qari'ah", suraNumber: 101, versesNum: 11),
//       SuraModel(suraNameAr: "التكاثر", suraNameEn: "At-Takathur", suraNumber: 102, versesNum: 8),
//       SuraModel(suraNameAr: "العصر", suraNameEn: "Al-Asr", suraNumber: 103, versesNum: 3),
//       SuraModel(suraNameAr: "الهمزة", suraNameEn: "Al-Humazah", suraNumber: 104, versesNum: 9),
//       SuraModel(suraNameAr: "الفيل", suraNameEn: "Al-Fil", suraNumber: 105, versesNum: 5),
//       SuraModel(suraNameAr: "قريش", suraNameEn: "Quraysh", suraNumber: 106, versesNum: 4),
//       SuraModel(suraNameAr: "الماعون", suraNameEn: "Al-Ma'un", suraNumber: 107, versesNum: 7),
//       SuraModel(suraNameAr: "الكوثر", suraNameEn: "Al-Kawthar", suraNumber: 108, versesNum: 3),
//       SuraModel(suraNameAr: "الكافرون", suraNameEn: "Al-Kafirun", suraNumber: 109, versesNum: 6),
//       SuraModel(suraNameAr: "النصر", suraNameEn: "An-Nasr", suraNumber: 110, versesNum: 3),
//       SuraModel(suraNameAr: "المسد", suraNameEn: "Al-Masad", suraNumber: 111, versesNum: 5),
//       SuraModel(suraNameAr: "الإخلاص", suraNameEn: "Al-Ikhlas", suraNumber: 112, versesNum: 4),
//       SuraModel(suraNameAr: "الفلق", suraNameEn: "Al-Falaq", suraNumber: 113, versesNum: 5),
//       SuraModel(suraNameAr: "الناس", suraNameEn: "An-Nas", suraNumber: 114, versesNum: 6),
//     ];
// }